USE labernoisdb;

INSERT INTO promotions_types (name, is_percentage_based, is_gift_based, is_exclusive, group_discount_travelers_count) VALUES
('Rabais en dollars', 0, 0, 0, 0),
('Rabais en dollars avec code', 0, 0, 1, 0),
('Rabais en pourcentage', 1, 0, 0, 0),
('Rabais en pourcentage avec code', 1, 0, 1, 0),
('Cadeau gratuit', 0, 1, 0, 0),
('Cadeau gratuit avec code', 0, 1, 0, 0),
('Rabais en dollars pour couple', 0, 0, 0, 2),
('Rabais en dollars avec code pour couple', 0, 0, 1, 2),
('Rabais en pourcentage pour couple', 1, 0, 0, 2),
('Rabais en pourcentage avec code pour couple', 1, 0, 1, 2),
('Cadeau gratuit pour couple', 0, 1, 0, 2),
('Cadeau gratuit avec code pour couple', 0, 1, 0, 2),
('Rabais en dollars pour famille', 0, 0, 0, 4),
('Rabais en dollars avec code pour famille', 0, 0, 1, 4),
('Rabais en pourcentage pour famille', 1, 0, 0, 4),
('Rabais en pourcentage avec code pour famille', 1, 0, 1, 4),
('Cadeau gratuit pour famille', 0, 1, 0, 4),
('Cadeau gratuit avec code pour famille', 0, 1, 0, 4),
('Rabais en dollars pour groupe de 10', 0, 0, 0, 10),
('Rabais en dollars avec code pour groupe de 10', 0, 0, 1, 10),
('Rabais en pourcentage pour groupe de 10', 1, 0, 0, 10),
('Rabais en pourcentage avec code pour groupe de 10', 1, 0, 1, 10),
('Cadeau gratuit pour groupe de 10', 0, 1, 0, 10),
('Cadeau gratuit avec code pour groupe de 10', 0, 1, 0, 10);
